name: ci

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build JAR file
        run: mvn package  # Replace with the appropriate build command for your project

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ahmadyazdi243
          password: 3030303an

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ahmadyazdi243/${{ github.event.repository.name }}
